### ISSUE TITLE
Updating the sapling

### ISSUE THREAD

**Issue by ktmn** [tameraydin/jquery-sapling#3]
If I run 

    $('#myList').sapling();

then update the list's HTML on the page during runtime, then run

    $('#myList').sapling();

again, it won't work. 

Is there any way to destroy sapling and then re initialize?

**Comment by tameraydin** [comment]
Unfortunately there is no any refresh/destroy or re-init methods. So with the current implementation only way to accomplish is removing the #myList from DOM and calling sapling() after re-appending.

Otherwise I agree that the plugin must provide one of those methods. Any PR is welcome.
